apiVersion: gateway.kyma-project.io/v2
kind: APIRule
metadata:
  name: sentiment-analysis-api-rule
spec:
  gateway: kyma-system/kyma-gateway
  hosts: 
  - cusrevwh-o
  service:
    name: customer-review-webhook
    port: 80
  rules:
  - jwt:
      authentications:
        - jwksUri: "{JWKS URL of your IDP}" #e.g. SAP Cloud Identity Tenant
          issuer: "{Your IDP address}" #e.g. SAP Cloud Identity Tenant
    methods:
    - POST
    path: /*