apiVersion: gateway.kyma-project.io/v2
kind: APIRule
metadata:
  name: cdp-extension
  namespace: cdp
spec:
  gateway: kyma-system/kyma-gateway
  hosts: 
  - cdp-extension
  service:
    name: cdp-extension
    port: 80
  rules:
  - path: /*
    methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "HEAD"]
    jwt:
      authentications:
      - jwksUri: https://accounts.DATA_CENTER/accounts.getJWTPublicKey?v2=true
        issuer: https://fidm.gigya.com/jwt/BUSINESS_UNIT_ID/
