apiVersion: gateway.kyma-project.io/v2
kind: APIRule
metadata:
  name: c4c-user-prop-xsuaa
spec:
  gateway: kyma-system/kyma-gateway
  hosts: 
  - c4c-user-prop-xsuaa
  rules:
    - path: /*
      noAuth: true
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - HEAD
        - PATCH
      service:
        name: app-auth-proxy
        port: 80
