apiVersion: gateway.kyma-project.io/v2
kind: APIRule
metadata:
  name: get-order
spec:
  gateway: kyma-system/kyma-gateway
  hosts:
  - get-order
  service:
    name: get-order
    port: 80
  rules:
    - path: /*
      noAuth: true
      methods:
        - GET