apiVersion: gateway.kyma-project.io/v2
kind: APIRule
metadata:
  name: cdc-subscription-webhook
  namespace: cdc
spec:
  gateway: kyma-system/kyma-gateway
  hosts:
  - cdc-subscription-webhook
  rules:
  - noAuth: true
    methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "HEAD"]
    path: /*
  service:
    name: cdc-subscription-webhook
    port: 80