apiVersion: gateway.kyma-project.io/v2
kind: APIRule
metadata:
  name: conference-registration-app
  namespace: conference-registration
spec:
  gateway: kyma-system/kyma-gateway
  hosts: 
  - conference-registration-app
  rules:
  - noAuth: true
    methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - HEAD
    path: /*
  service:
    name: conference-registration-app
    port: 80