apiVersion: gateway.kyma-project.io/v2
kind: APIRule
metadata:
  name: app-auth-proxy
spec:
  gateway: kyma-system/kyma-gateway
  hosts: 
  - app-auth-proxy
  service:
    name: app-auth-proxy
    port: 80
  rules:
    - path: /*
      noAuth: true
      methods: ["GET", "POST", "PUT", "DELETE", "HEAD", "PATCH"]
