apiVersion: gateway.kyma-project.io/v2
kind: APIRule
metadata:
  name: grpcorderserver
spec:
  gateway: kyma-system/kyma-gateway
  hosts: 
  - grpcorderserver
  service:
    name: grpcorderserver
    port: 50051
  rules:
  - path: /*
    noAuth: true
    methods:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
      - HEAD