apiVersion: gateway.kyma-project.io/v2
kind: APIRule
metadata:
  name: sample-extension-dotnet
spec:
  gateway: kyma-system/kyma-gateway
  hosts: 
  - sample-extension-dotnet
  rules:
    - noAuth: true
      methods:
        - GET
        - POST
        - PUT
        - DELETE
      path: /*
      service:
        name: sample-extension-dotnet
        port: 80