apiVersion: gateway.kyma-project.io/v2
kind: APIRule
metadata:
  name: hanadb-nodejs
spec:
  gateway: kyma-system/kyma-gateway
  hosts: 
  - hanadb-nodejs
  service:
    name: hanadb-nodejs
    port: 3000
  rules:
  - noAuth: true
    methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - HEAD
    path: /*
