---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-mssql-go
  labels:
    app: api-mssql-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-mssql-go
  template:
    metadata:
      labels:
        app: api-mssql-go
    spec:
      containers:
        # replace the repository URL with your own repository
        - image: jcawley5/api-mssql-go:latest
          imagePullPolicy: Always
          name: api-mssql-go
          ports:
            - name: http
              containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: api-mssql-go
  labels:
    app: api-mssql-go
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: api-mssql-go
---
apiVersion: gateway.kyma-project.io/v2
kind: APIRule
metadata:
  name: api-mssql-go
spec:
  gateway: kyma-system/kyma-gateway
  hosts: 
  - api-mssql-go
  service:
    name: api-mssql-go
    port: 80
  rules:
    - path: /orders/{**}
      noAuth: true
      methods: ["GET", "POST", "PUT", "DELETE"]