apiVersion: gateway.kyma-project.io/v2
kind: APIRule
metadata:
  name: sample-angular-app
spec:
  gateway: kyma-system/kyma-gateway
  hosts: 
  - sample-angular-app
  rules:
  - noAuth: true
    methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - HEAD
    path: /*
    service:
      name: kyma-identity-propagation-spa
      port: 80
