apiVersion: gateway.kyma-project.io/v2
kind: APIRule
metadata:
  name: sample-ui5-app
spec:
  gateway: kyma-system/kyma-gateway
  hosts: 
  - sample-ui5-app
  rules:
  - noAuth: true
    methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - HEAD
    path: /*
    service:
      name: kyma-identity-propagation-ui5
      port: 80
