apiVersion: gateway.kyma-project.io/v2
kind: APIRule
metadata:
  name: httpbin
spec:
  gateway: kyma-system/kyma-gateway
  hosts: 
  - httpbin
  rules:
  - jwt:
      authentications:
        - jwksUri: https://{sap-cloud-identity-tenant}.ondemand.com/oauth2/certs
          issuer: https://{sap-cloud-identity-tenant}.ondemand.com
    methods:
    - GET
    - HEAD
    path: /*
    service:
      name: httpbin
      port: 8000
