apiVersion: gateway.kyma-project.io/v2
kind: APIRule
metadata:
  name: cpi-scc-httpbin
spec:
  gateway: kyma-system/kyma-gateway
  hosts:
  - cpi-scc-httpbin
  service:
    name: cpi-scc-httpbin
    port: 80
  rules:
  - noAuth: true
    methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - HEAD
    path: /*