apiVersion: gateway.kyma-project.io/v2
kind: APIRule
metadata:
  name: sample-ldap
spec:
  gateway: kyma-system/kyma-gateway
  hosts: 
  - sample-ldap
  rules:
    - noAuth: true
      methods:
        - GET
      path: /*
      service:
        name: sample-ldap
        port: 8080