apiVersion: gateway.kyma-project.io/v2
kind: APIRule
metadata:
  name: daprwishlistappsdk
spec:
  gateway: kyma-system/kyma-gateway
  hosts: 
  - daprwishlistapp
  rules:
    - noAuth: true
      methods:
        - GET
        - POST
        - DELETE
      path: /*
  service:
    name: daprwishlistapp
    port: 7080
