apiVersion: gateway.kyma-project.io/v2
kind: APIRule
metadata:
  name: sample-extension-java
spec:
  gateway: kyma-system/kyma-gateway
  hosts: 
  - sample-extension-java
  rules:
    - noAuth: true
      methods:
        - GET
        - POST
        - PUT
        - DELETE
      path: /*
      service:
        name: sample-extension-java
        port: 8080