apiVersion: gateway.kyma-project.io/v2
kind: APIRule
metadata:
  name: test-in-cluster-events
  labels:
    scenario: in-cluster-events
spec:
  gateway: kyma-system/kyma-gateway
  hosts: 
  - test-in-cluster-events
  rules:
    - noAuth: true
      methods:
        - GET
      path: /*
      service:
        name: producer
        port: 80