apiVersion: gateway.kyma-project.io/v2
kind: APIRule
metadata:
  name: cpi-api-read-oauth
spec:
  gateway: kyma-system/kyma-gateway
  hosts:
  - cpi-api-read-oauth
  service:
    name: orders-list-api
    port: 80
  rules:
  - jwt:
      authentications:
        - issuer: <YOUR_ISSUER_URL>
          jwksUri: <YOUR_JWKS_URI>
    methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - HEAD
    path: /*