apiVersion: gateway.kyma-project.io/v2
kind: APIRule
metadata:
  name: cdc-extension
  namespace: cdc
spec:
  gateway: kyma-system/kyma-gateway
  hosts:
  - cdc-extension
  rules:
    - noAuth: true
      methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "HEAD"]
      path: /*
  service:
    name: cdc-extension
    port: 80
