apiVersion: gateway.kyma-project.io/v2
kind: APIRule
metadata:
  name: {{ .Values.services.srv.name }}
spec:
  gateway: {{ .Values.gateway }}
  hosts: 
  - {{ .Values.services.srv.name }}-{{ .Release.Namespace }}.{{ .Values.clusterDomain }}
  rules:
    - path: /*
      noAuth: true
      methods:
        - HEAD
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
  service:
    name: {{ .Values.services.srv.name }}
    port: {{ .Values.services.srv.port }}