apiVersion: gateway.kyma-project.io/v2
kind: APIRule
metadata:
  name: s4-address-validation
spec:
  gateway: kyma-system/kyma-gateway
  hosts: 
  - s4-address-validation
  service:
    name: s4-address-validation
    port: 80
  rules:
    - path: /*
      methods: ["DELETE", "HEAD", "GET", "PATCH", "POST", "PUT"]
      jwt:
        authentications:
        - issuer: <your-issuer-url>
          jwksUri: <your-jwks-uri>
