apiVersion: gateway.kyma-project.io/v2
kind: APIRule
metadata:
  name: app-your-domain-com
  namespace: conference-registration
  labels:
    app.kubernetes.io/name: app-your-domain-com
spec:
  gateway: conference-registration/app
  hosts: 
  - app.your-domain.com
  rules:
    - noAuth: true
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
        - HEAD
      path: /*
  service:
    name: conference-registration-app
    port: 80
