apiVersion: gateway.kyma-project.io/v2
kind: APIRule
metadata:
  name: cc-sample
spec:
  gateway: kyma-system/kyma-gateway
  hosts: 
  - cc-sample
  service:
    name: cc-sample
    port: 80
  rules:
  - noAuth: true
    methods:
    - GET
    - POST
    - PUT
    - DELETE
    - PATCH
    - HEAD
    path: /*
